ALTER TABLE users
  ADD COLUMN IF NOT EXISTS auth0_id TEXT,
  ALTER COLUMN email DROP NOT NULL,
  ALTER COLUMN name DROP NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS users_auth0_id_key ON users(auth0_id);