
services:
  app:
    build: .
    container_name: blog_api_app
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:16-alpine
    container_name: blog_api_db
    restart: always
    environment:
      POSTGRES_USER: jen
      POSTGRES_PASSWORD: jenjen
      POSTGRES_DB: examdb
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: